name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Use pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.16.1

      - name: Install and Build 🔧
        run: |
          pnpm install
          pnpm docs:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist
