name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.5.0

      - name: Install and Build packages only 🔧
        run: |
          pnpm install
          pnpm build:packages

      - name: Alias "npm" to "pnpm"
        run: |
          alias npm="pnpm"

      - name: Release "magner"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd magner
          pnpx semantic-release
